version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fruteria_trebol_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg://odoo:fruteria-el-trebol-db-2026@odoo_postgres:5432/trebol_db
      CORS_ORIGINS: "*"
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - postgresql_odoo-net

networks:
  postgresql_odoo-net:
    external: true
